add lib.sh file from polkadot to reuse existing functionality

diff --git a/.github/workflows/release-50_docker.yml b/.github/workflows/release-50_docker.yml
--- a/.github/workflows/release-50_docker.yml
+++ b/.github/workflows/release-50_docker.yml
@@ -49,55 +49,74 @@ jobs:
           chmod a+x $BINARY
           ls -al
 
+      - name: Fetch lib.sh from polkadot repo
+        working-directory: ${{ env.TMP }}
+        run: |
+          curl -O -L \
+            -H "Accept: application/vnd.github.v3.raw" \
+            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
+            https://raw.githubusercontent.com/paritytech/polkadot/master/scripts/ci/common/lib.sh
+
       - name: Check SHA256
         working-directory: ${{ env.TMP }}
         run: |
-          ls -al *$BINARY*
-          shasum -a 256 -c $BINARY.sha256
-          sha_result=$?
+          . ./lib.sh
 
-          echo sha_result: $sha_result
+          echo "Checking binary $BINARY"
+          check_sha256 $BINARY && echo "OK" || echo "ERR"
 
-          if [[ $sha_result -ne 0 ]]; then
-            echo "SHA256 check failed, exiting with error"
-            exit 1
-          else
-            echo "SHA256 check passed"
-          fi
+          # ls -al *$BINARY*
+          # shasum -a 256 -c $BINARY.sha256
+          # sha_result=$?
+
+          # echo sha_result: $sha_result
+
+          # if [[ $sha_result -ne 0 ]]; then
+          #   echo "SHA256 check failed, exiting with error"
+          #   exit 1
+          # else
+          #   echo "SHA256 check passed"
+          # fi
+
 
       - name: Check GPG
         working-directory: ${{ env.TMP }}
         run: |
-          KEY_PARITY_SEC=9D4B2B6EB8F97156D19669A9FF0812D491B96798
-          KEY_CHEVDOR=2835EAF92072BC01D188AF2C4A092B93E97CE1E2
-          KEY_EGOR=E6FC4D4782EB0FA64A4903CCDB7D3555DD3932D3
-          KEYSERVER=keyserver.ubuntu.com
+          . ./lib.sh
 
-          gpg --keyserver $KEYSERVER --receive-keys $KEY_PARITY_SEC
-          echo -e "5\ny\n" | gpg --no-tty --command-fd 0 --expert --edit-key $KEY_PARITY_SEC trust;
+          import_gpg_keys
+          check_gpg $BINARY
 
-          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
-              for key in $KEY_CHEVDOR $KEY_EGOR; do
-                (
-                  echo "Importing GPG key $key"
-                  gpg --no-tty --quiet --keyserver $GPG_KEYSERVER --recv-keys $key
-                  echo -e "4\ny\n" | gpg --no-tty --command-fd 0 --expert --edit-key $key trust;
-                ) &
-              done
-              wait
-          fi
+          # KEY_PARITY_SEC=9D4B2B6EB8F97156D19669A9FF0812D491B96798
+          # KEY_CHEVDOR=2835EAF92072BC01D188AF2C4A092B93E97CE1E2
+          # KEY_EGOR=E6FC4D4782EB0FA64A4903CCDB7D3555DD3932D3
+          # KEYSERVER=keyserver.ubuntu.com
 
-          gpg --no-tty --verify $BINARY.asc
-          gpg_result=$?
+          # gpg --keyserver $KEYSERVER --receive-keys $KEY_PARITY_SEC
+          # echo -e "5\ny\n" | gpg --no-tty --command-fd 0 --expert --edit-key $KEY_PARITY_SEC trust;
 
-          echo gpg_result: $gpg_result
+          # if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
+          #     for key in $KEY_CHEVDOR $KEY_EGOR; do
+          #       (
+          #         echo "Importing GPG key $key"
+          #         gpg --no-tty --quiet --keyserver $GPG_KEYSERVER --recv-keys $key
+          #         echo -e "4\ny\n" | gpg --no-tty --command-fd 0 --expert --edit-key $key trust;
+          #       ) &
+          #     done
+          #     wait
+          # fi
 
-          if [[ $gpg_result -ne 0 ]]; then
-            echo "GPG check failed, exiting with error"
-            exit 1
-          else
-            echo "GPG check passed"
-          fi
+          # gpg --no-tty --verify $BINARY.asc
+          # gpg_result=$?
+
+          # echo gpg_result: $gpg_result
+
+          # if [[ $gpg_result -ne 0 ]]; then
+          #   echo "GPG check failed, exiting with error"
+          #   exit 1
+          # else
+          #   echo "GPG check passed"
+          # fi
 
       - name: Build injected image
         env:
